import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { buildDemoPipeline, demoRiskContext } from './demo.js';
import { reconcilePaperEquity, updatePaperRisk } from '../layers/paper-portfolio.js';
import { evaluateRisk, sizePaperOrder } from '../layers/risk.js';

const FIXTURE_AT = '2026-01-01T00:05:00.000Z';
const DRAWDOWN_LIMITS = { dailyLossPct: 3, totalDrawdownPct: 8 } as const;

function snapshot(cashQuote: number, reservedQuote: number, asOf: string) {
  return reconcilePaperEquity({
    cashQuote, reservedQuote, realizedPnlQuote: 0, positions: [], openOrderIntentIds: [],
    marks: {}, asOf, maxMarkAgeMs: 60000,
  });
}

export interface PaperPreviewScenario {
  readonly id: 'capacity' | 'daily' | 'total' | 'approved';
  readonly title: string;
  readonly outcome: 'PASS' | 'REJECT';
  readonly equityQuote: number;
  readonly availableQuote: number;
  readonly maxNotionalQuote: number;
  readonly drawdownPct: number;
  readonly reason: string;
  readonly detail: string;
  readonly trace: readonly string[];
}

export interface PaperPreview {
  readonly mode: 'PAPER';
  readonly source: 'DETERMINISTIC_FIXTURE';
  readonly fixtureAsOf: string;
  readonly liveExecutionEnabled: false;
  readonly scenarios: readonly PaperPreviewScenario[];
}

/** UI read model generated by the same paper risk and strategy functions tested by the engine. */
export function makePaperPreview(): PaperPreview {
  const limits = demoRiskContext().limits;
  const tiny = updatePaperRisk(snapshot(17.32, 14.18, FIXTURE_AT), DRAWDOWN_LIMITS);
  let capacityReason = 'UNEXPECTED_PASS';
  try {
    sizePaperOrder({
      side: 'BUY', entryPrice: 100, stopLossPrice: 99, desiredQuantity: 1,
      quantityStep: 0.01, minNotionalQuote: 5,
    }, tiny, limits);
  } catch (error) {
    capacityReason = error instanceof Error ? error.message : String(error);
  }
  if (!capacityReason.includes('BELOW_MIN_NOTIONAL')) throw new Error('small-balance fixture unexpectedly passed');

  const initial = updatePaperRisk(snapshot(10000, 0, FIXTURE_AT), DRAWDOWN_LIMITS);
  const daily = updatePaperRisk(snapshot(9699, 0, '2026-01-01T00:07:00.000Z'), DRAWDOWN_LIMITS, initial);
  const peak = updatePaperRisk(snapshot(11000, 0, '2026-01-01T00:06:00.000Z'), DRAWDOWN_LIMITS, initial);
  const total = updatePaperRisk(snapshot(10100, 0, '2026-01-01T00:07:00.000Z'), DRAWDOWN_LIMITS, peak);
  const demo = buildDemoPipeline();
  const dailyDecision = evaluateRisk(demo.intent, demo.strategy, demoRiskContext({
    decidedAt: '2026-01-01T00:08:00.000Z', paperRisk: daily,
    portfolio: { ...demo.riskContext.portfolio, availableQuote: 9699, portfolioValueQuote: 9699 },
  }));
  const totalDecision = evaluateRisk(demo.intent, demo.strategy, demoRiskContext({
    decidedAt: '2026-01-01T00:08:00.000Z', paperRisk: total,
    portfolio: { ...demo.riskContext.portfolio, availableQuote: 10100, portfolioValueQuote: 10100 },
  }));
  return {
    mode: 'PAPER', source: 'DETERMINISTIC_FIXTURE', fixtureAsOf: FIXTURE_AT, liveExecutionEnabled: false,
    scenarios: [
      {
        id: 'capacity', title: 'SMALL BALANCE', outcome: 'REJECT',
        equityQuote: tiny.snapshot.equityQuote, availableQuote: tiny.snapshot.availableQuote,
        maxNotionalQuote: tiny.snapshot.equityQuote * limits.maxNotionalPctEquity / 100,
        drawdownPct: 0, reason: 'BELOW_MIN_NOTIONAL',
        detail: 'A $5 order minimum cannot fit beneath the equity cap or available quote funds. The risk limit stays in place.',
        trace: [`EQUITY $${tiny.snapshot.equityQuote.toFixed(2)}`, `FREE QUOTE $${tiny.snapshot.availableQuote.toFixed(2)}`,
          `25% CAP $${(tiny.snapshot.equityQuote * limits.maxNotionalPctEquity / 100).toFixed(2)}`, capacityReason],
      },
      {
        id: 'daily', title: 'DAILY LOSS PAUSE', outcome: dailyDecision.outcome === 'REJECT' ? 'REJECT' : 'PASS',
        equityQuote: daily.snapshot.equityQuote, availableQuote: daily.snapshot.availableQuote,
        maxNotionalQuote: daily.snapshot.equityQuote * limits.maxNotionalPctEquity / 100,
        drawdownPct: daily.dailyDrawdownPct, reason: daily.freezeReason ?? 'UNEXPECTED_PASS',
        detail: 'New paper entries pause for the UTC day. The open-position close path remains separate.',
        trace: [`DAY ANCHOR $${daily.dayStartEquityQuote.toFixed(2)}`, `EQUITY $${daily.snapshot.equityQuote.toFixed(2)}`,
          `DRAWDOWN ${daily.dailyDrawdownPct.toFixed(2)}%`, ...dailyDecision.reasons],
      },
      {
        id: 'total', title: 'TOTAL DRAWDOWN KILL', outcome: totalDecision.outcome === 'REJECT' ? 'REJECT' : 'PASS',
        equityQuote: total.snapshot.equityQuote, availableQuote: total.snapshot.availableQuote,
        maxNotionalQuote: total.snapshot.equityQuote * limits.maxNotionalPctEquity / 100,
        drawdownPct: total.totalDrawdownPct, reason: total.freezeReason ?? 'UNEXPECTED_PASS',
        detail: 'New paper entries stay blocked after the next day and after a serialized checkpoint restart.',
        trace: [`LIFETIME PEAK $${total.peakEquityQuote.toFixed(2)}`, `EQUITY $${total.snapshot.equityQuote.toFixed(2)}`,
          `DRAWDOWN ${total.totalDrawdownPct.toFixed(2)}%`, ...totalDecision.reasons],
      },
      {
        id: 'approved', title: 'APPROVED PAPER SIGNAL', outcome: demo.decision.outcome === 'PASS' ? 'PASS' : 'REJECT',
        equityQuote: demo.riskContext.paperRisk.snapshot.equityQuote,
        availableQuote: demo.riskContext.paperRisk.snapshot.availableQuote,
        maxNotionalQuote: demo.riskContext.paperRisk.snapshot.equityQuote * limits.maxNotionalPctEquity / 100,
        drawdownPct: 0, reason: demo.decision.reasons.join(' | '),
        detail: 'A thesis-linked legacy heuristic proposes BTC; the shared risk engine approves this paper fixture.',
        trace: [`STRATEGY ${demo.strategy.id}`, `INTENT ${demo.intent.id}`,
          `SIZE ${demo.intent.quantity} BTC`, `MODE ${demo.execution.mode}`, `RISK ${demo.decision.outcome}`],
      },
    ],
  };
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const preview = makePaperPreview();
  if (preview.scenarios.some((scenario) => scenario.outcome !== (scenario.id === 'approved' ? 'PASS' : 'REJECT'))) {
    throw new Error('paper preview scenario gates diverged from the risk engine');
  }
  writeFileSync('public/paper-preview.js', `window.TRADEDART_PAPER_PREVIEW = ${JSON.stringify(preview, null, 2)};\n`);
}
